services:
  - type: web
    name: music-bot
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python3 -m EsproMusic"
    envVars:
      - key: API_ID
        value: your_api_id
      - key: API_HASH
        value: your_api_hash
      - key: BOT_TOKEN
        value: your_bot_token
      - key: SESSION_STRING
        value: your_userbot_session
